kind: pipeline
name: test

steps:
- name: test
  image: nextcloudci/android:android-44
  privileged: true
  environment:
    LOG_USERNAME:
      from_secret: LOG_USERNAME
    LOG_PASSWORD:
      from_secret: LOG_PASSWORD
    GIT_USERNAME:
      from_secret: GIT_USERNAME
    GIT_TOKEN:
      from_secret: GIT_TOKEN
  commands:
    - exit 1

- name: notify
  image: drillster/drone-email
  host: $EMAIL_HOST
  port: 587
  username: $EMAIL_USERNAME
  password: $EMAIL_PASSWORD
  from: nextcloud-drone@kaminsky.me
  recipients_only: true
  recipients: $EMAIL_RECIPIENTS
  environment:
    EMAIL_USERNAME:
      from_secret: EMAIL_USERNAME
    EMAIL_PASSWORD:
      from_secret: EMAIL_PASSWORD
    EMAIL_RECIPIENTS:
      from_secret: EMAIL_RECIPIENTS
    EMAIL_HOST:
      from_secret: EMAIL_HOST
  when:
    status:
      - failure

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
